### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey saw your project on Twitter. Thought it would be cool to sort out the BOM to help people that want to build their own to buy the parts by putting it on Kitspace.

[Here is a preview](http://add-psx2amiga.preview.kitspace.org) of what it would look like. If you are happy to add it then I'll add it to Kitspace.org proper.

I had to plot the gerbers to make it compatible, which I know is not ideal, but we can't auto-plot them yet. I also wish we were able to easily switch in your PCBWay project URL for our generic PCBWay url. I'll open an issue on Kitspace for that.

### CODE REVIEW

**Comment by SukkoPera** [comment]
I'm sorry but I decided not to support this.

On one hand, it's a nice idea that makes life easier for people and I like that. But on the other hand, as I have already experienced in the past, making the gerbers readily available allows all the opportunists out there to make PCBs (or full boards with questionable soldering quality) and sell them at crazy prices (sometimes even removing license, credits and OSHW symbol). I have experienced that in the past and that really kills anyone's will to make open hardware, so I want to do all I can to stop them, while still keeping my stuff open. Having them need to generate the gerbers themselves seems to partially do the job, as most are people with no intelligence at all, who just grab all they can and try to make the most profit out of it.

Besides, the BOM is pretty short and I always try to use the most common components, so it shouldn't take long for anyone to find all the needed parts. I might also sell kits in the future (but I'm not too sure about that).

So again, sorry but I must decline this PR. You can still go on with your initiative, but I would ask you to understand my reasons and abort it.

**Comment by kasbah** [comment]
Thanks for responding and laying out your thoughts on it in detail. I respect your decision and have removed the preview. 

As you saw, Kitspace is just to automate some of the boring stuff people have to do when they want to rebuild your project. It's difficult to make things easier for people who are willing to contribute back without also making it easier for copycats. 

Having said that, I don't think Gerber generation and purchasing is what holds up copycats. If there is a market opportunity for your design then it will be filled. The best way to mitigate bad copies is by filling the opportunity yourself ideally by selling complete assemblies or kits. Short of that, make it as easy as possible for people to make it themselves! Of course putting it on Kitspace is just a small part of that, but it could help.

In the future we may be able to make it even easier for people by providing visual assembly aides and even linking to assembly services directly. How we do quality assurance there and how to make sure creators get their fair share, we still need to figure out before, but it could mean an easier way to fill the market gap for something and make it less viable for copycats.

Anyway, those are my thoughts on it. If you ever change your mind, and do want to put it up, just respond to this issue and I'll be notified.

**Comment by SukkoPera** [comment]
> The best way to mitigate bad copies is by filling the opportunity yourself ideally by selling complete assemblies or kits. Short of that, make it as easy as possible for people to make it themselves! Of course putting it on Kitspace is just a small part of that, but it could help.

Well, you have a point here. As I said, I like the idea, the only bit I don't like is having the gerbers ready for download. If you come up with a way of avoiding the need to disclose ready-made gerbers, I will be happy to add my project**s** (why not all of them? ;) ).

**Comment by kasbah** [comment]
I don't think we'll allow that as it ends up being a frustrating experience for the user. I'd rather have a uniform experience across all the projects. 

(I just experienced this with your project on the PCBWay site actually: I clicked the "download gerbers button", it said: "please login", I logged in, clicked it again, it said this user has not made gerbers available.)

What you can do by the way is pull in the 1-click-bom.csv as that can also be used from GitHub directly using [1-click BOM](https://github.com/kitspace/1clickBOM).

**Pull request closed without merging**
